di:
  diMdm:
    resources:
      requests:
        memory: "700Mi"
        cpu: "200m"
      limits:
        memory: "1000Mi"
        cpu: "1000m"
  diManager:
    resources:
      requests:
        memory: "1000Mi"
        cpu: "200m"
      limits:
        memory: "1250Mi"
        cpu: "500m"
  diOperator:
    resources:
      requests:
        memory: "150Mi"
        cpu: "75m"
      limits:
        memory: "1000Mi"
        cpu: "1000m"

diSubscriptionManagerIidr:
  resources:
    requests:
      memory: "700Mi"
      cpu: "200m"
    limits:
      memory: "1000Mi"
      cpu: "1000m"

diSubscriptionManagerS3:
  resources:
    requests:
      memory: "700Mi"
      cpu: "200m"
    limits:
      memory: "1000Mi"
      cpu: "1000m"

diSubscriptionManagerGS:
  resources:
    requests:
      memory: "700Mi"
      cpu: "200m"
    limits:
      memory: "1000Mi"
      cpu: "1000m"

grafana:
  resources:
    requests:
      memory: "200Mi"
      cpu: "75m"
    limits:
      memory: "400Mi"
      cpu: "150m"

iidrKafka:
  resources:
    requests:
      memory: "3000Mi"
      cpu: "500m"
    limits:
      memory: "3500Mi"
      cpu: "1000m"

influxdb:
  resources:
    requests:
      memory: "300Mi"
      cpu: "75m"
    limits:
      memory: "1000Mi"
      cpu: "1000m"

kafka:
  resources:
    requests:
      memory: "1800Mi"
      cpu: "1000m"
    limits:
      memory: "3000Mi"
      cpu: "1000m"

iidrAS:
  resources:
    requests:
      memory: "200Mi"
      cpu: "700m"
    limits:
      memory: "400Mi"
      cpu: "1000m"

redpanda:
  resources:
    requests:
      memory: "100Mi"
      cpu: "20m"
    limits:
      memory: "200Mi"
      cpu: "150m"

spacedeck:
  resources:
    requests:
      memory: "500Mi"
      cpu: "500m"
    limits:
      memory: "1000Mi"
      cpu: "500m"

manager:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "500m"
    limits:
      memory: "1200Mi"
      cpu: "1000m"

operator:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "500m"
    limits:
      memory: "1200Mi"
      cpu: "1000m"

service-creator:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "500m"
    limits:
      memory: "1600Mi"
      cpu: "1000m"

service-operator:
  resources:
    requests:
      memory: "1000Mi"
      cpu: "500m"
    limits:
      memory: "1500Mi"
      cpu: "1000m"
